// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/expenses": {
    params: {};
  };
  "/expenses/:expenseId": {
    params: {
      "expenseId": string;
    };
  };
  "/report": {
    params: {};
  };
  "/more": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/expenses" | "/expenses/:expenseId" | "/report" | "/more";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/expenses._index.tsx": {
    id: "routes/expenses._index";
    page: "/expenses";
  };
  "routes/expenses.$expenseId.tsx": {
    id: "routes/expenses.$expenseId";
    page: "/expenses/:expenseId";
  };
  "routes/report.tsx": {
    id: "routes/report";
    page: "/report";
  };
  "features/more/pages/MorePage.tsx": {
    id: "features/more/pages/MorePage";
    page: "/more";
  };
};