// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/expenses": {
    params: {};
  };
  "/expenses/:expenseId": {
    params: {
      "expenseId": string;
    };
  };
  "/expenses/add": {
    params: {};
  };
  "/report": {
    params: {};
  };
  "/more": {
    params: {};
  };
  "/reports/budget-goal": {
    params: {};
  };
  "/profile/nickname": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/expenses" | "/expenses/:expenseId" | "/expenses/add" | "/report" | "/more" | "/reports/budget-goal" | "/profile/nickname";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/expenses._index.tsx": {
    id: "routes/expenses._index";
    page: "/expenses";
  };
  "routes/expenses.$expenseId.tsx": {
    id: "routes/expenses.$expenseId";
    page: "/expenses/:expenseId";
  };
  "routes/expenses.add.tsx": {
    id: "routes/expenses.add";
    page: "/expenses/add";
  };
  "routes/report.tsx": {
    id: "routes/report";
    page: "/report";
  };
  "features/more/pages/MorePage.tsx": {
    id: "features/more/pages/MorePage";
    page: "/more";
  };
  "features/reports/pages/BudgetGoalPage.tsx": {
    id: "features/reports/pages/BudgetGoalPage";
    page: "/reports/budget-goal";
  };
  "features/profile/pages/NicknamePage.tsx": {
    id: "features/profile/pages/NicknamePage";
    page: "/profile/nickname";
  };
};